version: '3'

services:
  keycloak:
    build: ./keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak-realm.json
      DB_VENDOR: h2
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_LOGLEVEL: DEBUG
    volumes:
      - ./keycloak/keycloak-realm.json:/tmp/keycloak-realm.json
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
  minio:
    build: ./minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: password
      KEYCLOAK_IMPORT: /tmp/minio-realm.json
      MINIO_IDENTITY_OPENID_CONFIG_URL: http://192.168.1.65:8080/auth/realms/cyberduckrealm/.well-known/openid-configuration
      MINIO_IDENTITY_OPENID_CLIENT_ID: minio
      MINIO_IDENTITY_OPENID_CLIENT_SECRET: password
    command: server /data --console-address :9001
    depends_on:
      - keycloak

